
TebLocalPlannerROS:
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "circular"
    radius: 0.40 # for type "circular"
    # type: "line"
    # line_start: [-0.035, 0.0] # for type "line"
    # line_end: [0.035, 0.0] # for type "line"
    #front_offset: 0.2 # for type "two_circles"
    #front_radius: 0.2 # for type "two_circles"
    #rear_offset: 0.2 # for type "two_circles"
    #rear_radius: 0.2 # for type "two_circles"
    #vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

  acc_lim_theta: 1.0
  acc_lim_x: 0.6
  acc_lim_y: 0.3
  allow_init_with_backwards_motion: false
  cmd_angle_instead_rotvel: false
  costmap_obstacles_behind_robot_dist: 0.1
  dt_hysteresis: 0.1
  dt_ref: 0.1
  dynamic_obstacle_inflation_dist: 0.30
  enable_homotopy_class_planning: false
  enable_multithreading: true
  exact_arc_length: false
  feasibility_check_no_poses: 5
  force_reinit_new_goal_dist: 1.0
  free_goal_vel: false
  global_plan_overwrite_orientation: true
  global_plan_viapoint_sep: -0.1
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  include_costmap_obstacles: true
  include_dynamic_obstacles: false
  inflation_dist: 1.0
  is_footprint_dynamic: false
  legacy_obstacle_association: false
  max_global_plan_lookahead_dist: 3.0
  max_number_classes: 5
  max_vel_theta: 1.0
  max_vel_x: 0.6
  max_vel_x_backwards: 0.3
  max_vel_y: 0.3
  min_obstacle_dist: 0.5
  min_turning_radius: 0.0
  no_inner_iterations: 5
  no_outer_iterations: 4
  obstacle_association_cutoff_factor: 5.0
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_cost_exponent: 1.0
  obstacle_heading_threshold: 0.45
  obstacle_poses_affected: 30
  optimization_activate: true
  optimization_verbose: false
  oscillation_recovery: true
  penalty_epsilon: 0.8
  publish_feedback: false
  roadmap_graph_area_length_scale: 1.0
  roadmap_graph_area_width: 5.0
  roadmap_graph_no_samples: 15
  selection_alternative_time_cost: false
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 2.0
  selection_prefer_initial_plan: 0.95
  selection_viapoint_cost_scale: 1.0
  shrink_horizon_backup: true
  switching_blocking_period: 0.0
  teb_autosize: true
  via_points_ordered: false
  viapoints_all_candidates: true
  visualize_hc_graph: false
  visualize_with_time_as_z_axis_scale: 0.0
  weight_acc_lim_theta: 1.0
  weight_acc_lim_x: 1.0
  weight_acc_lim_y: 1.0
  weight_adapt_factor: 2.0
  weight_dynamic_obstacle: 50.0
  weight_dynamic_obstacle_inflation: 0.3
  weight_inflation: 0.4
  weight_kinematics_forward_drive: 10.0
  weight_kinematics_nh: 1000.0
  weight_kinematics_turning_radius: 1.0
  weight_max_vel_theta: 1.0
  weight_max_vel_x: 2.0
  weight_max_vel_y: 2.0
  weight_obstacle: 50.0
  weight_optimaltime: 1.0
  weight_shortest_path: 0.0
  weight_viapoint: 1.0
  wheelbase: 1.0
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.05
