<?xml version="1.0"?>
<!--
  Hexagon stacks
 -->
<robot name="stack_hexagons"
    xmlns:xacro="http://ros.org/wiki/xacro">


    <xacro:property name="cam_px" value="0.15" />
    <!-- <xacro:property name="cam_py" value="-0.0125" /> -->
    <xacro:property name="cam_pz" value="0.15" />
    <xacro:property name="cam_or" value="0" />
    <xacro:property name="cam_op" value="0" />
    <xacro:property name="cam_oy" value="0" />

    <!-- Xacro properties -->
    <xacro:property name="M_SCALE" value="0.001"/>

    <!-- Xacro macros -->
    <!-- Pole macros -->
    <xacro:macro name="stack_bottom_pole" params="parent number x_loc y_loc z_loc">
        <joint name="pole_bottom_${number}_joint" type="fixed">
            <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="pole_bottom_${number}_link"/>
        </joint>
        <link name="pole_bottom_${number}_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://turtlebot_description/meshes/stacks/hexagons/pole_bottom.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="0.0492" radius="0.006"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.008"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.000001686" ixy="0.0" ixz="0.0" iyy="0.000001686" iyz="0.0" izz="0.000000144"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:macro name="stack_middle_pole" params="parent number x_loc y_loc z_loc">
        <joint name="pole_middle_${number}_joint" type="fixed">
            <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
            <parent link="${parent}"/>
            <child link="pole_middle_${number}_link"/>
        </joint>
        <link name="pole_middle_${number}_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 ${M_PI} 0"/>
                <geometry>
                    <mesh filename="package://turtlebot_description/meshes/stacks/hexagons/pole_middle.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="0.0608" radius="0.006"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.012"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="0.000003805" ixy="0.0" ixz="0.0" iyy="0.000003805" iyz="0.0" izz="0.000000216"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:macro name="stack_laser_pole" params="parent x_loc y_loc z_loc length_coef">
        <joint name="stack_laser_pole_joint" type="fixed">
            <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
            <parent link="${parent}"/>
            <child link="stack_laser_pole_link"/>
        </joint>
        <link name="stack_laser_pole_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 ${M_PI} 0"/>
                <geometry>
                    <mesh filename="package://turtlebot_description/meshes/stacks/hexagons/pole_middle.dae" scale="1 1 ${length_coef}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${0.0608 * length_coef}" radius="0.006"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.012"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="0.000003805" ixy="0.0" ixz="0.0" iyy="0.000003805" iyz="0.0" izz="0.000000216"/>
            </inertial>
        </link>
    </xacro:macro>
    <!-- 
            Stack macro - all the components relative transforms are made with respect 
            to the parent link (usually base_link). They could be made relative to each
            other, but there is no necessary reason to do so.
        -->
    <xacro:macro name="stack_hexagons" params="parent">
        <stack_bottom_pole parent="${parent}" number="0" x_loc= "0.120" y_loc= "0.082" z_loc="0.1028"/>
        <stack_bottom_pole parent="${parent}" number="1" x_loc= "0.055" y_loc= "0.120" z_loc="0.1028"/>
        <stack_bottom_pole parent="${parent}" number="2" x_loc="-0.055" y_loc= "0.120" z_loc="0.1028"/>
        <stack_bottom_pole parent="${parent}" number="3" x_loc= "0.120" y_loc="-0.082" z_loc="0.1028"/>
        <stack_bottom_pole parent="${parent}" number="4" x_loc= "0.055" y_loc="-0.120" z_loc="0.1028"/>
        <stack_bottom_pole parent="${parent}" number="5" x_loc="-0.055" y_loc="-0.120" z_loc="0.1028"/>

        <joint name="plate_bottom_joint" type="fixed">
            <origin xyz="0.02364 0.0 0.1306" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="plate_bottom_link"/>
        </joint>
        <link name="plate_bottom_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://turtlebot_description/meshes/stacks/hexagons/plate_bottom.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="-0.02364 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="0.006" radius="0.170"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.520" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.003328" ixy="0.0" ixz="0.0" iyy="0.003328" iyz="0.0" izz="0.006656" />
            </inertial>
        </link>

        <stack_middle_pole parent="${parent}" number="0" x_loc= "0.0381" y_loc= "0.1505" z_loc="0.1640"/>
        <stack_middle_pole parent="${parent}" number="1" x_loc= "0.0381" y_loc="-0.1505" z_loc="0.1640"/>
        <!-- <stack_middle_pole parent="${parent}" number="2" x_loc="-0.0381" y_loc= "0.1505" z_loc="0.1640"/> -->
        <stack_middle_pole parent="${parent}" number="3" x_loc="-0.0381" y_loc="-0.1505" z_loc="0.1640"/>
        <stack_laser_pole parent="${parent}" x_loc="-0.0381" y_loc="0.1505" z_loc="0.2540" length_coef="4.0"/>

    </xacro:macro>
</robot>